# NumPy

NumPy (Numerical Python) è un package fondamentale per il calcolo scientifico specializzato nel lavorare con vettori e matrici.

Python fornisce :
* Tipi numerici ad alto livello (int, float, ...).
* Strutture dati : tuple, liste, dizionari.

Ma non fornisce modalità di lavoro tramite strutture dati che possono accogliere una mole di dati molto elevata.

NumPy arricchisce python introducendo:
* Una struttura dati array-multidimensionale
* Operazioni efficienti per lavorare su array-multidimensionali
* Operazioni di algebra lineare


Funzioni e operatori agiscono su vettori interi, raramente si adopereranno loop espliciti.
Gli elementi contenuti all'interno della struttura dati sono tutti **dello stesso tipo**.
Il codice è scritto in C ed è altamente ottimizzato.

OpenCV, che permette di elaborare immagini, adopera fortemente NumPy.

## Adoperare NumPy

NumPy è un modulo ed è convenzione importarlo con l'alias `np`.

In [2]:
import numpy as np
print(np.__version__) # Stampa versione corrente

1.20.3


## Classe ndarray

`ndarray` è un tipo di dato che è messo a disposizione dalla libreria che rappresenta un array multidimensionale omogeneo

In [5]:
x = np.array([1,2,3])
print(x.ndim)     # Numero dimensioni (assi)
print(x.shape)    # Numero elementi per dimensione
print(x.size)     # Numero elementi totale all'interno dell'array
print(x.dtype)    # Tipo di tutti gli elementi
print(x.itemsize) # Dimensione in byte di ciascun elemento
print(x.data)     # Buffer contenente gli elementi

1
(3,)
3
int64
8


In [8]:
a = np.array([[0,1,1,2,3], [5,8,13,21,34], [55,89,144,233,377]]) # np.array è il costruttore di default


print('type: ', type(a))  
print('ndim: ', a.ndim)  
print('shape:', a.shape)  
print('size: ', a.size)   
print('dtype:', a.dtype)
print('itemsize:', a.itemsize)

type:  <class 'numpy.ndarray'>
ndim:  2
shape: (3, 5)
size:  15
dtype: int64
itemsize: 8


Il tipo dell'array viene dedotto dagli elementi dell'array oppure può essere specificato nel secondo parametro della funzione ( dtype )


In [11]:
a = np.array([1,2,3]) 
print(a.dtype)
a2 = np.array([1,2,3], np.uint8)
print(a2.dtype)

int64
uint8


## Modi alternativi per creare array

La funzione empty permette di specificare la shape di un array ed un tipo di dato e alloca un array non inizializzato


In [12]:
a = np.empty((2,7), np.uint8)
print(a)

[[  0   0   0   0   0   0   0]
 [  0 126   0   0   0   1   0]]


Zeros / ones funzione come empty ma riempie l'array di zeri o di uno

In [14]:
zr = np.zeros((2,7))
ons = np.ones((2,7))
print(zr)
print(ons)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


arange crea un array monodimensionale con valori appartenenti ad un array

In [15]:
a = np.arange(100, 110, 2)
print(a)

[100 102 104 106 108]


identity permette di creare una matrice identità

In [ ]:
ide = np.identity(3)
print(ide)

## Tipi numerici
NumPy permette di specificare diverse varietà di tipologie di dati. Essendo una libreria scritta in C, tali tipologie corrispondono a quelle del linguaggio C.

## Operazioni di base
Tutte le operazioni sono **vettoriali**

In [25]:
a = np.array([25,36,49,64])
b = np.arange(4)

c = a - b          # Sottrazione elemento per elemento
print(c)

print(b**2)        # Elevamento alla seconda (adopera broadcasting)
print(np.sqrt(a))  # Radice quadrata degli elementi di a

# Confronti producono array di valori booleani con le stesse 
# dimensioni dell'array adoperato per i confronti 
print (a < 37)

b = np.array([25,37,49,63])
print(a == b)

[25 35 47 61]
[0 1 4 9]
[5. 6. 7. 8.]
[ True  True False False]
[ True False  True False]


## Prodotto
L'operatore di prodotto `*` viene adoperto come **prodotto elemento per elemento** mentre l'opertore `@` è usato per il prodotto fra matrici

In [28]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])


print(A * B)      # Prodotto elemento per elemento
print()
print(B @ B)      # Prodotto matriciale
print()

c = np.array([[1], [2], [3]])
e = np.array([[3,0,2]])

print(c @ e)      # (3,1) x (1,3) = (3,3)
print()
print(e @ c)      # (1,3) x (3,1) = (1,1)
print()


[[2 0]
 [0 4]]

[[ 4  0]
 [18 16]]

[[3 0 2]
 [6 0 4]
 [9 0 6]]

[[9]]



## Type cast
Tutti gli elementi di un array numpy sono dello stesso tipo ed è possibile attraverso una serie di funzioni andare a convertire quest'ultimo.
In un operazione tra array il tipo è convertito direttamente a quello più generale.


In [32]:
x = np.arange(-5,5,dtype=np.int32)
u = np.arange(10, dtype=np.uint32)

r = x + u
print(r.dtype)

int64


La funzione astype converte direttamente il tipo di un array

In [33]:
x.astype(np.uint8)

array([251, 252, 253, 254, 255,   0,   1,   2,   3,   4], dtype=uint8)

## Altre operazioni su array 

* `min()` : Ritorna l'elemento minimo dell'array
* `max()` : Ritorna l'lemento massimo dell'array
* `sum()` : Ritorna la somma di tutti gli elementi dell'array

**Nota:** E' possibile specificare anche se queste operazioni devono essere fatte solamente sulle righe o solamente sulle colonne attraverso il parametro axis (0 = righe, 1 = colonne).




## Funzioni universali
Sono funzioni che lavorano elemento per elemento.

Sono:
* Operazioni matematiche: sum, subtract, multiply, etc..
* Operazioni trigonometriche: sin, cos, tan, etc..
* Operazioni bitwise: bitwise_and, bitwise_or, bitwise_not
* Operazioni di confronto: greater, greater_equal, less, less_equal, etc...
* Operazioni floating point: isfinite, isinf, isnan, fabs, etc..

## Slicing su array
Su array monodimensionale lo slicing funziona esattamente allo stesso modo di quello che si adopera per le tuple e le liste.

In [38]:
a = np.arange(10) ** 3
print(a[2]) # Accesso al terzo elemento dell'array

print(a[2:5]) # Dal terzo elemento al quinto

a[:6:2] = 42 # Modifica valore dell'array in determinate posizioni

print(a[::-1]) # Ordine inverso

a[::2] += a[1::2]
print(a)


a[:] = -1 # Modifica tutti gli elementi
print(a)

8
[ 8 27 64]
[729 512 343 216 125  42  27  42   1  42]
[  43    1   69   27  167  125  559  343 1241  729]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


Su array multidimensionali occorre specificare degli indici per ogni dimensione

In [44]:
a = np.fromfunction(lambda i,j : i * 10 + j, (3,5), dtype=int)

print(a)
print(a[2,3])

# Posso usare per ogni dimensione lo slicing
print(a[:2,2])

# Seleziona tutta la colonna 2
print(a[:,1])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
23
[ 2 12]
[ 1 11 21]
